tap "homebrew/bundle"
tap "homebrew/services"

brew "curl"
brew "ffmpeg"
brew "gh"
brew "httpie"
brew "yt-dlp"
brew "docker"
brew "mas"

cask "karabiner-elements"
cask "cursor"
cask "1password"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "arc"
cask "cleanshot"
cask "alt-tab"
cask "bettertouchtool"
cask "copilot"
cask "discord"
cask "docker"
cask "imageoptim"
cask "pocket-casts"
cask "postico"
cask "raycast"
cask "slack"
cask "steam"
cask "typora"
cask "uhk-agent"
cask "warp"
cask "bartender"
cask "betterdisplay"
cask "daisydisk"
cask "hakuneko"
cask "kindle-comic-converter"
cask "prusaslicer"
cask "sip"
cask "xtool-creative-space"

# davinci resolve
mas "davinci resolve", id: 571213070
